# Setup
title:               Seo-Donghyun's blog
tagline:             'git blog'
description:         'A reserved <a href="https://jekyllrb.com" target="_blank">Jekyll</a> theme that places the utmost gravity on content with a hidden drawer. Made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
url:                 https://seo-donghyun.github.io/
# baseurl:             ''
paginate:            5
permalink:           pretty
comments:            true

# About/contact
author:
  name:              Seo-Donghyun
  url:               https://github.com/Seo-Donghyun/Seo-Donghyun.github.io
  email:             peterpan1103@kookmin.ac.kr

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
comment:
  provider:          "disqus"
  disqus:
    shortname:       "seo-donghyun"
