# Setup
title:               Seo-Donghyun's blog
tagline:             'git blog'
description:         ""
url:                 https://seo-donghyun.github.io/
# baseurl:             ''
paginate:            5
permalink:           pretty
comments:            true

# About/contact
author:
  name:              Seo-Donghyun
  url:               https://github.com/Seo-Donghyun/Seo-Donghyun.github.io
  email:             peterpan1103@kookmin.ac.kr
  message:           Hello, welcome to my blog.
  student_ID:        20223091

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: UA-250403528-1
comment:
  provider:          "disqus"
  disqus:
    shortname:       "seo-donghyun"
